#!/usr/bin/env bash
#Requirements 1)Install nginx on server
#2) Nginx should be listening on port 80
#3) When querying Nginx at its root / with a GET request (requesting a page) using curl, 
#it must return a page that contains the string Hello World!

#script that configures a new Ubuntu machine to respect above requirements 
#You can’t use systemctl for restarting nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service restart nginx
