#!/usr/bin/env bash
# Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '51i\           location /redirect_me {\n               return 301 htt
ps://www.youtube.com/watch?v=QH2-TGUlwu4;\n         }' /etc/nginx/sites-enabled/default
sudo service nginx start
