#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sh -c  'echo "Ceci n'"'"'est pas une page" > /var/www/html/custom_404.html'
sudo sed -i '47i\           location /redirect_me {\n               return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n         }\n\t error_page 404    /custom_404.html;\n' /etc/nginx/sites-enabled/default
sudo service nginx restart
