#!/usr/bin/python3
"""top_articles module"""
import requests


def recurse(subreddit, hot_list=[]):
    """lists top titles"""
    headers = {"User-Agent": 'MyPythonScript/1.0'}
    url = f"https://www.reddit.com/r/{subreddit}/hot.json?limit=10"

    res = requests.get(url, headers=headers)

    if res.status_code == 200:
        top_ten = res.json().get("data").get("childeren")
        if top_ten is None:
            print("None")
        else:
            for top in top_ten:
                print(top.get("data").get("title"))
    else:
        print("None")
