#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

list_dir=$ls

for item in list_dir
do
    echo 
done