#!/usr/bin/env bash
# script that makes user nginx not root
sudo sed -i 's/user www-data/user nginx/'  /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
